### ISSUE TITLE
Get an error

### ISSUE THREAD

**Issue by wptop-net** [sabhirajanand/google-drive-folder-download-with-resume-support#1]
I get the following error when input folder ID

**Comment by sabhirajanand** [comment]
the error you faced might be due to wrong folder id entered.

when you open a folder in your google drive, just see the url there you will get the folder id.

for example:-
if folder url is: https://drive.google.com/drive/folders/1C0BV9Kz4BZteXjkOjXbYCDFPBSIHyq

then your folder id is: 1C0BV9Kz4BZteXjkOjXbYCDFPBSIHyq
